name: commit-alert
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install
      - name: set variables
        id: variables
        run: |
          echo ::set-output name=username::$GITHUB_ACTOR
          echo ::set-output name=repository::$GITHUB_REPOSITORY
      - name: Check last commit
        uses: ./ # Uses an action in the root directory
        id: check-commit
        with:
          username: ${{ steps.variables.outputs.username }}
          repository: ${{ steps.variables.outputs.repository }}

      - name: post uncommitted message
        if: steps.check-commit.outputs.committed == 'false'
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          username: '잔디 지키미 2'
          icon_emoji: ':herb:'
          channel: '@naheenosaur'
          payload: |
            {
                text: "오늘의 커밋을 잊지 마세요 ! :herb:",
            }

      - name: post committed message
        if: steps.check-commit.outputs.committed == 'true'
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          username: '잔디 지키미 2'
          icon_emoji: ':herb:'
          channel: '@naheenosaur'
          payload: |
            {
                text: "오늘 커밋 하셨네요 !! :herb:",
            }
