name: commit-alert
on:
  schedule:
    - cron:  '0 14 * * *' # UTC time

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install
      - name: set variables
        id: variables
        run: |
          echo ::set-output name=username::$GITHUB_ACTOR
          echo ::set-output name=repository::$GITHUB_REPOSITORY

      - name: Check last commit
        uses: ./ # Uses an action in the root directory
        id: check-commit
        with:
          username: ${{ steps.variables.outputs.username }}
          repository: ${{ steps.variables.outputs.repository }}
          timezone: 'Asia/Seoul'

      - name: Post uncommitted message
        if: steps.check-commit.outputs.committed == 'false'
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
                text: "오늘의 커밋을 잊지 마세요 ! :herb:",
            }

      - name: Post committed message
        if: steps.check-commit.outputs.committed == 'true'
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
                text: "오늘 커밋 하셨네요 !! :herb:",
            }

      - name: Build github page
        if: steps.check-commit.outputs.committed == 'true'
        run: |
          mkdir public
          cat > public/index.html << EOL
          ${{ steps.check-commit.outputs.github-page }}
          EOL
          touch .nojekyll

      - name: Deploy
        if: steps.check-commit.outputs.committed == 'true'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
