name: commit-alert
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install
      - name: Check last commit
        uses: ./ # Uses an action in the root directory
        id: check-commit
        with:
          username: 'naheenosaur'